### PR TITLE
Make update support files a code transform command

### PR DESCRIPTION
**Pull request by ddgenome**
Disable autofix for now and register the update support files
transform to a command.  I did not implement running `tslint --fix`
after updating the file because the tslint autofix should still do
that.  Will this result in a PR that automatically merges if the
resulting goal set completes successfully?

### CODE REVIEW

**Comment by jessitron** [comment]
I don't think we have auto-merge but maybe @johnsonr has implemented that and I don't know about it?

**Comment by cdupuis** [comment]
We sure have auto merge for transforms. I added some time ago. It is called build aware and works with markers in the commit message. See 
https://github.com/atomist/atomist-sdm/blob/master/lib/transform/tryToUpdateAtomistDependencies.ts#L124 and a BranchCommit as transformPresentation. See the TransformCommandRegistration in the same file.

**Comment by ddgenome** [comment]
The branch names generated by BranchCommit in client are not unique-ified in any way?

**Comment by cdupuis** [comment]
> The branch names generated by BranchCommit in client are not unique-ified in any way?

No, we usually use Date.now() as the suffix of a branch name.

**Comment by ddgenome** [comment]
What did you mean by "static branch name" then?

**Comment by cdupuis** [comment]
> What did you mean by "static branch name" then?

Static in that it doesn’t depend on parameters to the transform or from its execution.

**Comment by ddgenome** [comment]
Makes sense, thanks. So if I don't care about the branch name, I can just extend the automation-client BranchCommit, overriding the message accessor to include those tags?

**Comment by cdupuis** [comment]
Yeah, BranchCommit is just an interface in client: 
https://github.com/atomist/automation-client/blob/391f62b0c417519335ac0226c15f8aa5319c4570/lib/operations/edit/editModes.ts#L60

So you can just return that type from the transformPresentation.

**Comment by ddgenome** [comment]
I think I have made the appropriate changes.

**Pull request merged**
